# Generated by Django 4.0.5 on 2022-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_turns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
